version: "3.7"

services:
  httpd:
    build: ./docker/httpd
    volumes:
      - /var/www/html
    ports:
      - "9090:80"

  mysql:
    build: ./docker/mysql
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=asdf1234