version: "3.7"

services:
  apache:
    build: ./docker/apache
    volumes:
      - /var/www/html
    ports:
      - "9090:80"
      - "9091:443"

  mysql:
    image: mysql:8.0.22
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_DATABASE=zeroboard
      - MYSQL_ROOT_PASSWORD=asdf1234